//! Result caching around selected checks through moon (the cmnp adapter).
//!
//! Each selected check becomes one moon task whose command is the ordinary
//! `ccid check` for that check. moon hashes the task's inputs, skips work whose
//! inputs already passed, and can share results through a remote cache. ccid keeps
//! owning check semantics, budgets and receipts; moon only adds result reuse.
//! The moon configuration is generated for each run and is not committed to the
//! repository; the remote cache address comes from `CCID_REMOTE_CACHE`.
use crate::{
    event, failure, load_manifest, select_checks, value, Check, Environment, Result, Runner,
    SOURCE_REVISION,
};
use serde_json::json;
use sha2::{Digest, Sha256};
use std::{
    collections::BTreeMap,
    fs,
    path::Path,
    time::{Duration, Instant},
};

const MARKER: &str = "# ccid-generated: regenerated by `ccid cached` on every run; do not edit.";
const RESULTS: &str = ".ccid/results";
/// Every `ccid check` locks the repository's target cache, so tasks run one at a time.
const MUTEX: &str = "ccid-target";

/// Run the selected checks through moon so unchanged inputs reuse earlier results.
pub fn run_cached(
    repo: &Path,
    manifest: &Path,
    selectors: &[String],
    plan: bool,
    force: bool,
) -> Result<()> {
    let root = repo.canonicalize()?;
    let (parsed, bytes) = load_manifest(&root, manifest)?;
    let selected = select_checks(&parsed, selectors)?;
    for name in &selected {
        task_id(name)?;
        validate_cache_inputs(&parsed.checks[name])?;
        for output in &parsed.checks[name].cache_outputs {
            crate::source::safe_relative(Path::new(output))?;
            if output.starts_with('.') || output.contains(['*', '?', '[', ']']) {
                return Err(failure(
                    "Cached outputs must be explicit, non-hidden relative paths",
                ));
            }
        }
        for command in &parsed.checks[name].cache_tools {
            crate::validate_command(command)?;
        }
    }
    let project = project_id(&parsed.project);
    let environment: Environment = std::env::vars_os().collect();
    let remote = remote_cache(&environment)?;
    let manifest_arg = manifest
        .to_str()
        .ok_or_else(|| failure("Manifest path must be valid UTF-8"))?;
    event(
        json!({"event":"cached-plan","project":project,"checks":selected,
        "remote_cache":remote.is_some(),"force":force,
        "source_commit":value(&environment,"CI_COMMIT_SHA"),
        "manifest_sha256":format!("{:x}",Sha256::digest(&bytes)),"tool_revision":SOURCE_REVISION}),
    );
    if plan {
        return Ok(());
    }
    let runner = Runner::new(root.clone(), environment.clone(), Duration::from_secs(120))?;
    let moon_version = runner.run(&argv(&["moon", "--version"]), true)?;
    let path_ccid = runner.run(&argv(&["ccid", "source-revision"]), true)?;
    if path_ccid != SOURCE_REVISION {
        return Err(failure(format!(
            "The ccid on PATH ({path_ccid}) must be this revision ({SOURCE_REVISION}); cached results are keyed on it"
        )));
    }
    let mut identities = BTreeMap::new();
    let mut probes = BTreeMap::new();
    for name in &selected {
        let identity = tool_identity(&runner, &parsed.checks[name], &environment, &mut probes)?;
        identities.insert(name.clone(), identity);
    }
    event(json!({"event":"cached-identity","moon":moon_version,"identities":identities}));

    write_generated(
        &root.join(".moon/workspace.yml"),
        &render_workspace(&project),
    )?;
    write_generated(
        &root.join("moon.yml"),
        &render_tasks(&parsed.checks, &selected, manifest_arg, &identities),
    )?;
    // Results are task outputs: a cache hit restores them, a miss writes them fresh.
    let results = root.join(RESULTS);
    if results.exists() {
        fs::remove_dir_all(&results)?;
    }

    let mut moon_environment = environment;
    // Transport configuration must not change task hashes between schedulers.
    // moon supports configuring its cache endpoint without rewriting workspace files.
    if let Some(url) = remote {
        moon_environment.insert("MOON_REMOTE_HOST".into(), url.clone().into());
        moon_environment.insert(
            "MOON_REMOTE_API".into(),
            if url.starts_with("http") {
                "http"
            } else {
                "grpc"
            }
            .into(),
        );
        moon_environment.insert("MOON_REMOTE_CACHE_COMPRESSION".into(), "zstd".into());
    }
    let mut command = argv(&["moon", "run"]);
    command.extend(selected.iter().map(|name| format!("{project}:{name}")));
    if force {
        command.push("--force".into());
    }
    let timeout = value(&moon_environment, "CI_TIMEOUT")
        .and_then(|v| v.parse::<u64>().ok())
        .unwrap_or(2700);
    let started = Instant::now();
    Runner::new(root, moon_environment, Duration::from_secs(timeout))?.run(&command, false)?;
    event(
        json!({"event":"cached-finish","checks":selected,"seconds":started.elapsed().as_secs_f64()}),
    );
    Ok(())
}

fn argv(args: &[&str]) -> Vec<String> {
    args.iter().map(|s| (*s).to_owned()).collect()
}

/// moon task identifiers: letters, digits, dash and underscore.
fn task_id(name: &str) -> Result<&str> {
    let valid = name
        .bytes()
        .next()
        .is_some_and(|b| b.is_ascii_alphanumeric())
        && name
            .bytes()
            .all(|b| b.is_ascii_alphanumeric() || b == b'-' || b == b'_');
    if valid {
        Ok(name)
    } else {
        Err(failure(format!(
            "Check name {name:?} is not usable as a cached task; use letters, digits, '-' or '_'"
        )))
    }
}

/// moon project identifiers do not allow dots; manifest slugs may contain them.
fn project_id(slug: &str) -> String {
    slug.replace('.', "-")
}

/// The remote cache endpoint, from the runner environment (never from the repository).
fn remote_cache(environment: &Environment) -> Result<Option<String>> {
    match value(environment, "CCID_REMOTE_CACHE") {
        None => Ok(None),
        Some(url)
            if ["grpc://", "grpcs://", "http://", "https://"]
                .iter()
                .any(|scheme| url.starts_with(scheme)) =>
        {
            Ok(Some(url))
        }
        Some(_) => Err(failure(
            "CCID_REMOTE_CACHE must start with grpc://, grpcs://, http:// or https://",
        )),
    }
}

/// Validate repository-relative file globs. Environment and commit inputs have
/// dedicated fields so they cannot accidentally bypass the commit opt-in.
fn validate_cache_inputs(check: &Check) -> Result<()> {
    if check.cache_env.iter().any(|key| key == "CI_COMMIT_SHA") && !check.cache_commit {
        return Err(failure("CI_COMMIT_SHA requires cache_commit = true; remove it from cache_env for content-only checks"));
    }
    if let Some(inputs) = &check.cache_inputs {
        if inputs.is_empty() || !inputs.iter().any(|input| !input.starts_with('!')) {
            return Err(failure(
                "cache_inputs requires at least one positive file pattern",
            ));
        }
        for input in inputs {
            let path = input.strip_prefix('!').unwrap_or(input);
            crate::source::safe_relative(Path::new(path))?;
            if path.is_empty() || path.contains(['$', '@', '\\', ':', '\0']) {
                return Err(failure(
                    "cache_inputs accepts repository-relative file patterns only",
                ));
            }
        }
    }
    Ok(())
}

/// Identity is per check: selecting a commit-sensitive build must not invalidate
/// a content-only test. Probe each distinct tool only once across the selection.
fn tool_identity(
    runner: &Runner,
    check: &Check,
    environment: &Environment,
    probe_results: &mut BTreeMap<Vec<String>, String>,
) -> Result<String> {
    let mut parts = vec![
        format!("ccid {SOURCE_REVISION}"),
        format!(
            "platform {} {}",
            std::env::consts::OS,
            std::env::consts::ARCH
        ),
        format!(
            "linker {}",
            value(environment, "CI_LINKER").unwrap_or_else(|| "system".into())
        ),
        // Bind the entire declaration even when narrow globs exclude the manifest.
        serde_json::to_string(check)?,
    ];
    for key in &check.cache_env {
        if key != "CI_COMMIT_SHA" {
            parts.push(format!("env {key} {:?}", value(environment, key)));
        }
    }
    if check.cache_commit {
        let commit = value(environment, "CI_COMMIT_SHA")
            .filter(|commit| commit.len() == 40 && commit.bytes().all(|b| b.is_ascii_hexdigit()))
            .ok_or_else(|| failure("cache_commit requires an exact CI_COMMIT_SHA"))?;
        parts.push(format!("commit {commit}"));
    }
    let mut probes = check.cache_tools.clone();
    match check.kind.as_str() {
        "cargo" => match check.toolchain.as_deref().unwrap_or("system") {
            "system" => {
                probes.push(argv(&["rustc", "-vV"]));
                probes.push(argv(&["cargo", "--version"]));
            }
            toolchain => {
                probes.push(argv(&["rustup", "run", toolchain, "rustc", "-vV"]));
                probes.push(argv(&["rustup", "run", toolchain, "cargo", "--version"]));
            }
        },
        "javascript" => {
            probes.push(argv(&["node", "--version"]));
            let manager = check.manager.as_deref().unwrap_or("npm");
            probes.push(vec![
                crate::checks::javascript_executable(manager, cfg!(windows)).to_owned(),
                "--version".into(),
            ]);
        }
        "nix" => probes.push(argv(&["nix", "--version"])),
        _ => {}
    }
    probes.sort();
    probes.dedup();
    for probe in probes {
        if !probe_results.contains_key(&probe) {
            probe_results.insert(probe.clone(), runner.run(&probe, true)?);
        }
        parts.push(format!(
            "{}: {}",
            serde_json::to_string(&probe)?,
            probe_results[&probe]
        ));
    }
    Ok(format!("{:x}", Sha256::digest(parts.join("\n").as_bytes())))
}

fn render_workspace(project: &str) -> String {
    let mut projects = serde_json::Map::new();
    projects.insert(project.to_owned(), json!("."));
    let workspace = json!({
        "projects": projects,
        "vcs": { "client": "git" },
    });
    // YAML is a superset of JSON, so the generated JSON is valid moon YAML.
    format!(
        "{MARKER}\n{}\n",
        serde_json::to_string_pretty(&workspace).unwrap_or_default()
    )
}

fn render_tasks(
    checks: &std::collections::BTreeMap<String, Check>,
    selected: &[String],
    manifest: &str,
    identities: &BTreeMap<String, String>,
) -> String {
    let mut tasks = serde_json::Map::new();
    for name in selected {
        let receipt = format!("{RESULTS}/{name}.jsonl");
        let mut outputs = checks[name].cache_outputs.clone();
        outputs.push(receipt.clone());
        let mut inputs = checks[name]
            .cache_inputs
            .clone()
            .unwrap_or_else(|| argv(&["**/*"]));
        inputs.extend(argv(&[
            "!.git/**",
            "!.moon/**",
            "!moon.yml",
            "!.ccid/**",
            "!target/**",
            "$CCID_TOOL_IDENTITY",
        ]));
        for check in checks.values() {
            for output in &check.cache_outputs {
                inputs.push(format!("!{output}"));
                inputs.push(format!("!{output}/**"));
            }
        }
        tasks.insert(
            name.clone(),
            json!({
                "command": ["ccid", "check", "--repo", ".", "--manifest", manifest, "--check", name],
                "env": { "CCID_RECEIPT": receipt, "CCID_TOOL_IDENTITY": identities[name] },
                "inputs": inputs,
                "outputs": outputs,
                "options": { "runFromWorkspaceRoot": true, "mutex": MUTEX }
            }),
        );
    }
    format!(
        "{MARKER}\n{}\n",
        serde_json::to_string_pretty(&json!({ "tasks": tasks })).unwrap_or_default()
    )
}

/// Write a generated file, refusing to overwrite a configuration someone else owns.
fn write_generated(path: &Path, content: &str) -> Result<()> {
    if path.exists() && !fs::read_to_string(path)?.starts_with(MARKER) {
        return Err(failure(format!(
            "{} exists and was not generated by ccid; refusing to overwrite",
            path.display()
        )));
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, content)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn task_ids_follow_moon_rules() {
        assert!(task_id("test").is_ok());
        assert!(task_id("registry-publisher").is_ok());
        assert!(task_id("a_b2").is_ok());
        assert!(task_id("").is_err());
        assert!(task_id("-lead").is_err());
        assert!(task_id("has.dot").is_err());
        assert!(task_id("sp ace").is_err());
    }

    #[test]
    fn project_ids_drop_dots() {
        assert_eq!(project_id("example.org"), "example-org");
        assert_eq!(project_id("ccid"), "ccid");
    }

    #[test]
    fn remote_cache_comes_from_environment_only() {
        let mut environment = Environment::new();
        assert_eq!(remote_cache(&environment).unwrap(), None);
        environment.insert("CCID_REMOTE_CACHE".into(), "grpc://cache:9092".into());
        assert_eq!(
            remote_cache(&environment).unwrap().as_deref(),
            Some("grpc://cache:9092")
        );
        environment.insert("CCID_REMOTE_CACHE".into(), "cache:9092".into());
        assert!(remote_cache(&environment).is_err());
    }

    #[test]
    fn workspace_is_independent_of_remote_transport() {
        let local: serde_json::Value =
            serde_json::from_str(render_workspace("demo").split_once('\n').unwrap().1).unwrap();
        assert_eq!(local["projects"]["demo"], ".");
        assert!(local.get("remote").is_none());
    }

    #[test]
    fn tasks_wrap_ccid_check_with_receipt_output() {
        let checks = std::collections::BTreeMap::from([(
            "test".into(),
            Check {
                cache_outputs: vec!["binary".into()],
                ..Check::default()
            },
        )]);
        let text = render_tasks(
            &checks,
            &["test".into()],
            ".ci/ccid.toml",
            &BTreeMap::from([("test".into(), "identity".into())]),
        );
        assert!(text.starts_with(MARKER));
        let tasks: serde_json::Value =
            serde_json::from_str(text.split_once('\n').unwrap().1).unwrap();
        let task = &tasks["tasks"]["test"];
        assert_eq!(
            task["command"],
            json!([
                "ccid",
                "check",
                "--repo",
                ".",
                "--manifest",
                ".ci/ccid.toml",
                "--check",
                "test"
            ])
        );
        assert_eq!(
            task["outputs"],
            json!(["binary", ".ccid/results/test.jsonl"])
        );
        assert!(task["inputs"]
            .as_array()
            .unwrap()
            .contains(&json!("!binary")));
        assert_eq!(task["options"]["mutex"], MUTEX);
        assert!(task["inputs"]
            .as_array()
            .unwrap()
            .contains(&json!("$CCID_TOOL_IDENTITY")));
    }

    fn identity(check: &Check, environment: &Environment) -> String {
        let directory = tempfile::tempdir().unwrap();
        let runner = Runner::new(
            directory.path().into(),
            environment.clone(),
            Duration::from_secs(5),
        )
        .unwrap();
        tool_identity(&runner, check, environment, &mut BTreeMap::new()).unwrap()
    }

    #[test]
    fn commits_and_branches_do_not_invalidate_content_checks() {
        let check = Check {
            cache_env: vec!["GOFLAGS".into()],
            ..Check::default()
        };
        let mut environment = Environment::new();
        environment.insert("CI_COMMIT_SHA".into(), "a".repeat(40).into());
        environment.insert("CI_COMMIT_BRANCH".into(), "main".into());
        let original = identity(&check, &environment);
        environment.insert("CI_COMMIT_SHA".into(), "b".repeat(40).into());
        environment.insert("CI_COMMIT_BRANCH".into(), "other".into());
        assert_eq!(identity(&check, &environment), original);
        environment.insert("GOFLAGS".into(), "-race".into());
        assert_ne!(identity(&check, &environment), original);
    }

    #[test]
    fn commit_sensitive_check_does_not_poison_other_check_identities() {
        let content = Check::default();
        let stamp = Check {
            cache_commit: true,
            ..Check::default()
        };
        let mut environment = Environment::new();
        environment.insert("CI_COMMIT_SHA".into(), "a".repeat(40).into());
        let original = identity(&content, &environment);
        let stamped = identity(&stamp, &environment);
        environment.insert("CI_COMMIT_SHA".into(), "b".repeat(40).into());
        assert_ne!(identity(&stamp, &environment), stamped);
        assert_eq!(identity(&content, &environment), original);
        let directory = tempfile::tempdir().unwrap();
        let runner = Runner::new(
            directory.path().into(),
            Environment::new(),
            Duration::from_secs(5),
        )
        .unwrap();
        assert!(tool_identity(&runner, &stamp, &Environment::new(), &mut BTreeMap::new()).is_err());
    }

    #[test]
    fn tool_versions_linker_and_check_definition_remain_inputs() {
        let probe = argv(&["example-tool", "--version"]);
        let mut check = Check {
            cache_tools: vec![probe.clone()],
            ..Check::default()
        };
        let directory = tempfile::tempdir().unwrap();
        let mut environment = Environment::new();
        let runner = Runner::new(
            directory.path().into(),
            environment.clone(),
            Duration::from_secs(5),
        )
        .unwrap();
        let mut probes = BTreeMap::from([(probe.clone(), "v1".into())]);
        let original = tool_identity(&runner, &check, &environment, &mut probes).unwrap();
        probes.insert(probe.clone(), "v2".into());
        assert_ne!(
            tool_identity(&runner, &check, &environment, &mut probes).unwrap(),
            original
        );
        probes.insert(probe, "v1".into());
        environment.insert("CI_LINKER".into(), "mold".into());
        assert_ne!(
            tool_identity(&runner, &check, &environment, &mut probes).unwrap(),
            original
        );
        environment.clear();
        check.commands = vec![argv(&["different-command"])];
        assert_ne!(
            tool_identity(&runner, &check, &environment, &mut probes).unwrap(),
            original
        );
    }

    #[test]
    fn narrow_inputs_preserve_exclusions_and_check_identity() {
        let check: Check =
            toml::from_str("cache_inputs = ['src/**', 'Cargo.*', '!src/generated/**']").unwrap();
        validate_cache_inputs(&check).unwrap();
        let checks = BTreeMap::from([("test".into(), check)]);
        let identities = BTreeMap::from([("test".into(), "identity".into())]);
        let text = render_tasks(&checks, &["test".into()], ".ci/ccid.toml", &identities);
        let tasks: serde_json::Value =
            serde_json::from_str(text.split_once('\n').unwrap().1).unwrap();
        let inputs = tasks["tasks"]["test"]["inputs"].as_array().unwrap();
        for required in [
            "src/**",
            "Cargo.*",
            "!src/generated/**",
            "!.git/**",
            "!.moon/**",
            "!.ccid/**",
            "!target/**",
            "$CCID_TOOL_IDENTITY",
        ] {
            assert!(inputs.contains(&json!(required)));
        }
        assert!(!inputs.contains(&json!("**/*")));
        assert_eq!(
            tasks["tasks"]["test"]["env"]["CCID_TOOL_IDENTITY"],
            "identity"
        );
        for inputs in [
            vec![],
            vec!["!docs/**"],
            vec!["../outside"],
            vec!["/absolute"],
            vec![""],
            vec!["$CI_COMMIT_SHA"],
            vec!["@group(source)"],
        ] {
            let check = Check {
                cache_inputs: Some(inputs.into_iter().map(str::to_owned).collect()),
                ..Check::default()
            };
            assert!(validate_cache_inputs(&check).is_err());
        }
        let check = Check {
            cache_env: vec!["CI_COMMIT_SHA".into()],
            ..Check::default()
        };
        assert!(validate_cache_inputs(&check).is_err());
    }

    #[test]
    fn generated_files_never_overwrite_foreign_configuration() {
        let directory = tempfile::tempdir().unwrap();
        let path = directory.path().join("moon.yml");
        fs::write(&path, "tasks: {}\n").unwrap();
        assert!(write_generated(&path, &format!("{MARKER}\n{{}}\n")).is_err());
        fs::write(&path, format!("{MARKER}\nold\n")).unwrap();
        assert!(write_generated(&path, &format!("{MARKER}\nnew\n")).is_ok());
        assert!(fs::read_to_string(&path).unwrap().ends_with("new\n"));
    }
}
