//! Deterministic adapters for the existing staged-job execution contract.
use crate::{failure, jobs, load_manifest, Result};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::{
    collections::BTreeMap,
    fs,
    io::Write,
    path::{Path, PathBuf},
};

const GENERATOR: &str = "ccid render v1";
const CROW_MARKER: &str = "# Generated by ccid render v1; edit .ci/ccid.toml instead.\n";
const INVENTORY: &str = ".ci/jobs.json";

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Config {
    pub tool_revision: String,
}

#[derive(Debug, Serialize)]
pub struct Report {
    pub checked: bool,
    pub files: Vec<PathBuf>,
    pub removed: Vec<PathBuf>,
}

#[derive(Serialize)]
struct Inventory<'a> {
    schema: u32,
    generator: &'static str,
    tool_revision: &'a str,
    manifest_sha256: String,
    jobs: BTreeMap<String, jobs::Plan>,
}

/// Render repository jobs, or check byte-for-byte drift without modifying files.
/// This creates manual Crow execution adapters, not a forge event dispatcher.
pub fn render(repo: &Path, manifest: &Path, check: bool) -> Result<Report> {
    // execute-job reads this exact path from its verified source archive.
    if manifest != Path::new(".ci/ccid.toml") {
        return Err(failure("Job adapters require .ci/ccid.toml"));
    }
    let (parsed, bytes) = load_manifest(repo, manifest)?;
    let config = parsed
        .render
        .as_ref()
        .ok_or_else(|| failure("Manifest requires [render].tool_revision"))?;
    if config.tool_revision.len() != 40
        || !config
            .tool_revision
            .bytes()
            .all(|b| b.is_ascii_digit() || (b'a'..=b'f').contains(&b))
    {
        return Err(failure(
            "Rendered tool revision must be a full lowercase Git SHA",
        ));
    }
    if parsed.jobs.is_empty() {
        return Err(failure("Rendering requires at least one declared job"));
    }
    let mut inventory = Inventory {
        schema: 1,
        generator: GENERATOR,
        tool_revision: &config.tool_revision,
        manifest_sha256: format!("{:x}", Sha256::digest(&bytes)),
        jobs: BTreeMap::new(),
    };
    let mut outputs = BTreeMap::new();
    for name in parsed.jobs.keys() {
        let plan = jobs::plan(repo, manifest, name, None)?;
        outputs.insert(
            PathBuf::from(format!(".crow/{}.yaml", plan.workflow)),
            include_str!("render/crow.yaml").replace("CCID_TOOL_REVISION", &config.tool_revision),
        );
        inventory.jobs.insert(name.clone(), plan);
    }
    outputs.insert(
        PathBuf::from(INVENTORY),
        serde_json::to_string_pretty(&inventory)? + "\n",
    );

    // Validate the whole destination set before any writes or directory creation.
    for directory in [".ci", ".crow"] {
        if let Some(metadata) = metadata(&repo.join(directory))? {
            if !metadata.is_dir() || metadata.file_type().is_symlink() {
                return Err(failure(format!("Unsafe adapter directory: {directory}")));
            }
        }
    }
    let mut drift = Vec::new();
    for (relative, expected) in &outputs {
        let path = repo.join(relative);
        if let Some(metadata) = metadata(&path)? {
            if !metadata.is_file() || metadata.file_type().is_symlink() {
                return Err(failure(format!(
                    "Unsafe adapter file: {}",
                    relative.display()
                )));
            }
            let actual = fs::read_to_string(path)?;
            if !owned(relative, &actual) {
                return Err(failure(format!(
                    "Refusing to overwrite foreign adapter: {}",
                    relative.display()
                )));
            }
            if actual != *expected {
                drift.push(relative.clone());
            }
        } else {
            drift.push(relative.clone());
        }
    }
    let obsolete = obsolete(repo, &outputs)?;
    if fs::read(repo.join(manifest))? != bytes {
        return Err(failure("Manifest changed during job rendering"));
    }
    if check && (!drift.is_empty() || !obsolete.is_empty()) {
        let paths = drift
            .iter()
            .chain(&obsolete)
            .map(|path| path.display().to_string())
            .collect::<Vec<_>>()
            .join(", ");
        return Err(failure(format!(
            "Generated job adapters have drifted: {paths}"
        )));
    }
    if !check {
        for relative in &drift {
            let path = repo.join(relative);
            let parent = path
                .parent()
                .expect("Generated paths have parent directories");
            fs::create_dir_all(parent)?;
            let mut temporary = tempfile::NamedTempFile::new_in(parent)?;
            temporary.write_all(outputs[relative].as_bytes())?;
            temporary.persist(path)?;
        }
        for relative in &obsolete {
            fs::remove_file(repo.join(relative))?;
        }
    }
    Ok(Report {
        checked: check,
        files: outputs.into_keys().collect(),
        removed: obsolete,
    })
}

fn metadata(path: &Path) -> Result<Option<fs::Metadata>> {
    match fs::symlink_metadata(path) {
        Ok(value) => Ok(Some(value)),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(None),
        Err(error) => Err(error.into()),
    }
}

fn owned(path: &Path, content: &str) -> bool {
    if path == Path::new(INVENTORY) {
        serde_json::from_str::<serde_json::Value>(content)
            .ok()
            .and_then(|value| value.get("generator").cloned())
            .is_some_and(|value| value.as_str() == Some(GENERATOR))
    } else {
        content.starts_with(CROW_MARKER)
    }
}

fn obsolete(repo: &Path, outputs: &BTreeMap<PathBuf, String>) -> Result<Vec<PathBuf>> {
    let directory = repo.join(".crow");
    if !directory.exists() {
        return Ok(Vec::new());
    }
    let mut obsolete = Vec::new();
    for entry in fs::read_dir(directory)? {
        let entry = entry?;
        let relative = Path::new(".crow").join(entry.file_name());
        if outputs.contains_key(&relative)
            || !matches!(
                relative.extension().and_then(|v| v.to_str()),
                Some("yaml" | "yml")
            )
        {
            continue;
        }
        // Never follow or delete an unrelated symlink or directory.
        if entry.file_type()?.is_file() {
            let bytes = fs::read(entry.path())?;
            if bytes.starts_with(CROW_MARKER.as_bytes()) {
                obsolete.push(relative);
            }
        }
    }
    obsolete.sort();
    Ok(obsolete)
}
