//! Deterministic adapters for the existing staged-job execution contract.
use crate::{failure, jobs, load_manifest, Result};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::{
    collections::BTreeMap,
    fs,
    io::Write,
    path::{Path, PathBuf},
};

const GENERATOR: &str = "ccid render v1";
const CROW_MARKER: &str = "# Generated by ccid render v1; edit .ci/ccid.toml instead.\n";
const INVENTORY: &str = ".ci/jobs.json";

/// Workflow variables the shared adapter template already declares. Auxiliary
/// source variables must not collide with these; a test pins this set to the
/// template below, so template evolution cannot silently reopen a collision.
const TEMPLATE_VARIABLES: [&str; 11] = [
    "CCID_JOB_REQUEST",
    "CI_MEMORY_MB",
    "CI_MEMORY_PER_JOB_MB",
    "CI_MIN_AVAILABLE_MB",
    "CI_REPOSITORY_URL",
    "CI_TOOL_ARCHIVE",
    "CI_TOOL_BINARY",
    "CI_TOOL_BINARY_SHA256",
    "CI_TOOL_SHA256",
    "SOURCE_ARCHIVE",
    "SOURCE_SHA256",
];

/// Auxiliary source declared in `.ci/archives.toml` or `.ci/live-inputs.toml`,
/// mirroring the dispatch helper's pinned-source schema (names, workflow
/// scoping). Render emits only variable declarations; kinds, revisions,
/// digests and defaults are validated but not emitted, so they are not stored.
struct PinnedSource {
    archive_variable: String,
    digest_variable: String,
    workflows: Option<Vec<String>>,
}

fn valid_archive_name(name: &str) -> bool {
    let mut chars = name.chars();
    match chars.next() {
        Some(first) if first.is_ascii_lowercase() => {}
        _ => return false,
    }
    let mut len = 1;
    for c in chars {
        if !(c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_' || c == '-') {
            return false;
        }
        len += 1;
        if len > 48 {
            return false;
        }
    }
    true
}

fn valid_workflow_name(name: &str) -> bool {
    let mut chars = name.chars();
    match chars.next() {
        Some(first) if first.is_ascii_alphanumeric() => {}
        _ => return false,
    }
    chars.all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '.' || c == '-')
}

fn valid_aux_variable(value: &str, suffix: &str) -> bool {
    let mut chars = value.chars();
    match chars.next() {
        Some(first) if first.is_ascii_uppercase() => {}
        _ => return false,
    }
    if !value
        .bytes()
        .all(|byte| byte.is_ascii_uppercase() || byte.is_ascii_digit() || byte == b'_')
    {
        return false;
    }
    if value.starts_with("CI_") || value.starts_with("CROW_") {
        return false;
    }
    value.ends_with(suffix)
}

fn valid_revision(revision: &str, kind: &str) -> bool {
    if revision.len() == 40
        && revision
            .bytes()
            .all(|byte| byte.is_ascii_hexdigit() && !byte.is_ascii_uppercase())
    {
        return true;
    }
    kind == "git-bundle" && revision == "source"
}

/// Read and validate `.ci/archives.toml`. Absence means no auxiliary sources;
/// any present file must satisfy the schema or rendering fails closed.
fn pinned_sources(repo: &Path) -> Result<BTreeMap<String, PinnedSource>> {
    let text = match fs::read_to_string(repo.join(".ci/archives.toml")) {
        Ok(text) => text,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(BTreeMap::new()),
        Err(error) => return Err(error.into()),
    };
    let value: toml::Value = toml::from_str(&text)
        .map_err(|error| failure(format!("Invalid .ci/archives.toml: {error}")))?;
    let table = value
        .as_table()
        .ok_or_else(|| failure("Invalid .ci/archives.toml schema"))?;
    if table.len() != 2
        || table.get("schema").and_then(toml::Value::as_integer) != Some(1)
        || !table
            .get("archives")
            .is_some_and(|archives| archives.is_table())
    {
        return Err(failure("Invalid .ci/archives.toml schema"));
    }
    let mut sources = BTreeMap::new();
    let mut declared = std::collections::BTreeSet::new();
    let archives = table["archives"].as_table().expect("archives is a table");
    for (name, item) in archives {
        if !valid_archive_name(name) {
            return Err(failure(format!("Invalid pinned source name: {name}")));
        }
        let item = item
            .as_table()
            .ok_or_else(|| failure(format!("Invalid pinned source declaration: {name}")))?;
        let mut keys: Vec<&String> = item.keys().collect();
        keys.sort();
        let mut expected = vec!["archive_variable", "digest_variable", "revision"];
        let has_kind = item.contains_key("kind");
        let has_workflows = item.contains_key("workflows");
        if has_kind {
            expected.push("kind");
        }
        if has_workflows {
            expected.push("workflows");
        }
        expected.sort();
        if keys != expected {
            return Err(failure(format!(
                "Invalid pinned source declaration: {name}"
            )));
        }
        let kind = match item.get("kind") {
            None => "archive".to_owned(),
            Some(value) => value
                .as_str()
                .filter(|kind| *kind == "archive" || *kind == "git-bundle")
                .ok_or_else(|| failure(format!("Invalid pinned source kind: {name}")))?
                .to_owned(),
        };
        let _revision = item
            .get("revision")
            .and_then(toml::Value::as_str)
            .filter(|revision| valid_revision(revision, &kind))
            .ok_or_else(|| failure(format!("Invalid pinned source revision: {name}")))?;
        let suffix = if kind == "git-bundle" {
            "_SOURCE_BUNDLE"
        } else {
            "_SOURCE_ARCHIVE"
        };
        let archive_variable = item
            .get("archive_variable")
            .and_then(toml::Value::as_str)
            .filter(|variable| valid_aux_variable(variable, suffix))
            .ok_or_else(|| failure(format!("Invalid pinned source variables: {name}")))?
            .to_owned();
        let digest_variable = item
            .get("digest_variable")
            .and_then(toml::Value::as_str)
            .filter(|variable| valid_aux_variable(variable, "_SOURCE_SHA256"))
            .ok_or_else(|| failure(format!("Invalid pinned source variables: {name}")))?
            .to_owned();
        for variable in [archive_variable.clone(), digest_variable.clone()] {
            if TEMPLATE_VARIABLES.contains(&variable.as_str()) || !declared.insert(variable.clone())
            {
                return Err(failure(format!(
                    "Pinned source variable reserved or duplicated: {variable}"
                )));
            }
        }
        let workflows = if has_workflows {
            let list = item["workflows"]
                .as_array()
                .ok_or_else(|| failure(format!("Invalid pinned source workflows: {name}")))?;
            if list.is_empty() {
                return Err(failure(format!("Invalid pinned source workflows: {name}")));
            }
            let mut workflows = Vec::new();
            for entry in list {
                let workflow = entry
                    .as_str()
                    .filter(|workflow| valid_workflow_name(workflow))
                    .ok_or_else(|| failure(format!("Invalid pinned source workflows: {name}")))?;
                workflows.push(workflow.to_owned());
            }
            let mut sorted = workflows.clone();
            sorted.sort();
            sorted.dedup();
            if sorted.len() != workflows.len() {
                return Err(failure(format!("Invalid pinned source workflows: {name}")));
            }
            Some(workflows)
        } else {
            None
        };
        sources.insert(
            name.clone(),
            PinnedSource {
                archive_variable,
                digest_variable,
                workflows,
            },
        );
    }
    Ok(sources)
}

/// Read `.ci/live-inputs.toml` through the shared strict parser and merge
/// its staged-file inputs into the declaration map, so workflow adapters
/// declare them identically to `.ci/archives.toml` kinds. Absence means no
/// live inputs. Digests and defaults are validated by the shared parser and
/// enforced at runtime by Rust; render emits only variable declarations.
fn live_inputs(repo: &Path) -> Result<BTreeMap<String, PinnedSource>> {
    let Some(manifest) = crate::tor_inputs::load_manifest(repo)? else {
        return Ok(BTreeMap::new());
    };
    let mut sources = BTreeMap::new();
    let mut declared = std::collections::BTreeSet::new();
    for (name, input) in &manifest.live_inputs {
        for variable in [&input.archive_variable, &input.digest_variable] {
            if TEMPLATE_VARIABLES.contains(&variable.as_str()) || !declared.insert(variable.clone())
            {
                return Err(failure(format!(
                    "Live input variable reserved or duplicated: {variable}"
                )));
            }
        }
        sources.insert(
            name.clone(),
            PinnedSource {
                archive_variable: input.archive_variable.clone(),
                digest_variable: input.digest_variable.clone(),
                workflows: input.workflows.clone(),
            },
        );
    }
    Ok(sources)
}

/// Placeholder for the comma-separated gating jobs in generated status steps.
const GATING_PLACEHOLDER: &str = "CCID_GATING_JOBS";

/// Render one workflow adapter, appending declared auxiliary variables that
/// apply to it. Output is byte-identical to the plain template when none apply.
fn workflow_adapter(
    tool_revision: &str,
    workflow: &str,
    sources: &BTreeMap<String, PinnedSource>,
) -> Result<String> {
    let template = include_str!("render/crow.yaml").replace("CCID_TOOL_REVISION", tool_revision);
    let mut extra = Vec::new();
    for source in sources.values() {
        if let Some(workflows) = &source.workflows {
            if !workflows.iter().any(|name| name == workflow) {
                continue;
            }
        }
        extra.push(format!("  {}: {{default: \"\"}}", source.archive_variable));
        extra.push(format!("  {}: {{default: \"\"}}", source.digest_variable));
    }
    if extra.is_empty() {
        return Ok(template);
    }
    let (head, tail) = template
        .split_once("\nsteps:")
        .ok_or_else(|| failure("Adapter template has no steps section"))?;
    Ok(format!("{head}\n{}\nsteps:{tail}", extra.join("\n")))
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Config {
    pub tool_revision: String,
    /// Crow repo secret holding the immutable prebuilt tool path.
    #[serde(default = "default_tool_secret_binary")]
    pub tool_secret_binary: String,
    /// Crow repo secret holding the tool path's sha256.
    #[serde(default = "default_tool_secret_binary_sha256")]
    pub tool_secret_binary_sha256: String,
    /// Optional resolver credential projection.
    ///
    /// When present, render adds ONLY this fixed entry to the repository-job
    /// step environment (never to native-status steps):
    /// `CFRG_RESOLVER_FORGEJO_TOKEN: { from_secret: <name> }`.
    /// This is a secret *reference* (name only); values are never embedded.
    /// Absent by default: rendered output is byte-identical to the unopted
    /// template. The referenced repository secret must already be configured
    /// for the selected repository; ccid never distributes tokens fleet-wide.
    /// Contribution checks (no secret configured) render unchanged.
    /// No operator hostnames appear here.
    #[serde(default)]
    pub resolver_token_secret: Option<String>,
}

fn default_tool_secret_binary() -> String {
    "CI_TOOL_BINARY_STATIC".into()
}

fn default_tool_secret_binary_sha256() -> String {
    "CI_TOOL_BINARY_SHA256_STATIC".into()
}

fn validate_secret_name(value: &str) -> Result<()> {
    if value.is_empty()
        || value.contains("CCID")
        || !value
            .bytes()
            .all(|c| c.is_ascii_uppercase() || c.is_ascii_digit() || c == b'_')
    {
        return Err(failure(
            "Tool secret names must be plain uppercase identifiers",
        ));
    }
    Ok(())
}

/// A dependency push fan-out declaration: this repository's push events run
/// the consumer's repository-owned job with the event commit pinned.
#[derive(Debug, Deserialize, Serialize, Clone)]
#[serde(deny_unknown_fields)]
pub struct PushConsumer {
    /// Consumer forge URL (https, ssh, or scp-like; never credentials).
    pub consumer: String,
    /// This repository's branch whose pushes trigger the consumer run.
    pub branch: String,
    /// Consumer branch fetched and executed.
    pub consumer_branch: String,
    /// Consumer job name executed for the event.
    pub job: String,
    /// This repository's package name inside the consumer graph.
    pub self_name: String,
}

#[derive(Debug, Serialize)]
struct ConsumerPlan {
    consumer: String,
    branch: String,
    consumer_branch: String,
    job: String,
    self_name: String,
}

const RESOLVER_TOKEN_ENV: &str = "CFRG_RESOLVER_FORGEJO_TOKEN";

#[derive(Debug, Serialize)]
pub struct Report {
    pub checked: bool,
    pub files: Vec<PathBuf>,
    pub removed: Vec<PathBuf>,
}

#[derive(Serialize)]
struct Inventory<'a> {
    schema: u32,
    generator: &'static str,
    tool_revision: &'a str,
    manifest_sha256: String,
    jobs: BTreeMap<String, jobs::Plan>,
    /// Fan-out declarations; skipped when empty so manual-only inventories
    /// render byte-identical to before.
    #[serde(skip_serializing_if = "BTreeMap::is_empty")]
    push_consumers: BTreeMap<String, ConsumerPlan>,
}

/// Render repository jobs, or check byte-for-byte drift without modifying files.
/// Manual Crow execution adapters come from job workflows; push execution
/// adapters come from job push opt-ins and consumer fan-out declarations.
pub fn render(repo: &Path, manifest: &Path, check: bool) -> Result<Report> {
    // execute-job reads this exact path from its verified source archive.
    if manifest != Path::new(".ci/ccid.toml") {
        return Err(failure("Job adapters require .ci/ccid.toml"));
    }
    let (parsed, bytes) = load_manifest(repo, manifest)?;
    let config = parsed
        .render
        .as_ref()
        .ok_or_else(|| failure("Manifest requires [render].tool_revision"))?;
    if config.tool_revision.len() != 40
        || !config
            .tool_revision
            .bytes()
            .all(|b| b.is_ascii_digit() || (b'a'..=b'f').contains(&b))
    {
        return Err(failure(
            "Rendered tool revision must be a full lowercase Git SHA",
        ));
    }
    if let Some(secret) = config.resolver_token_secret.as_deref() {
        validate_resolver_token_secret(secret)?;
    }
    if parsed.jobs.is_empty() {
        return Err(failure("Rendering requires at least one declared job"));
    }
    let mut inventory = Inventory {
        schema: 1,
        generator: GENERATOR,
        tool_revision: &config.tool_revision,
        manifest_sha256: format!("{:x}", Sha256::digest(&bytes)),
        jobs: BTreeMap::new(),
        push_consumers: BTreeMap::new(),
    };
    let mut sources = pinned_sources(repo)?;
    for (name, source) in live_inputs(repo)? {
        if sources.insert(name.clone(), source).is_some() {
            return Err(failure(format!(
                "Live input name collides with a pinned source: {name}"
            )));
        }
    }
    let mut outputs = BTreeMap::new();
    let gating = gating_jobs(&parsed)?;
    for name in parsed.jobs.keys() {
        let plan = jobs::plan(repo, manifest, name, None)?;
        outputs.insert(
            PathBuf::from(format!(".crow/{}.yaml", plan.workflow)),
            inject_gating(
                inject_resolver_token(
                    workflow_adapter(&config.tool_revision, &plan.workflow, &sources)?,
                    &config.tool_revision,
                    config.resolver_token_secret.as_deref(),
                )?,
                &gating,
            )?,
        );
        inventory.jobs.insert(name.clone(), plan);
    }
    // Push adapters are keyed per job and branch so the event carries no job
    // selection: the filename and baked command name it. Only opted-in jobs
    // take the filename rules; manual-only jobs keep their existing names.
    // The CCID_ prefix is reserved so substituted values can never
    // reintroduce a placeholder. Secret validation runs only when push
    // files are actually emitted, so manual-only manifests never see it.
    let repository = parsed
        .repository
        .as_deref()
        .filter(|url| !url.contains("CCID") && crate::cache::canonical_repository(url).is_ok());
    for name in parsed.jobs.keys() {
        let planned = jobs::plan(repo, manifest, name, None)?;
        if planned.push_branches.is_empty() {
            continue;
        }
        validate_push_name(name)?;
        validate_secret_name(&config.tool_secret_binary)?;
        validate_secret_name(&config.tool_secret_binary_sha256)?;
        let consumer =
            repository.ok_or_else(|| failure("Push adapters require a manifest repository URL"))?;
        for branch in &planned.push_branches {
            let filename = format!(".crow/push-{name}-{branch}.yaml");
            if outputs.contains_key(&PathBuf::from(&filename)) {
                return Err(failure(format!("Duplicate push adapter: {filename}")));
            }
            outputs.insert(
                PathBuf::from(filename),
                substitute(
                    include_str!("render/push.yaml"),
                    config,
                    &[
                        ("CCID_PUSH_BRANCH", branch.as_str()),
                        ("CCID_PUSH_JOB", name.as_str()),
                        ("CCID_CONSUMER_URL", consumer),
                    ],
                ),
            );
        }
    }
    for (name, consumer) in &parsed.push_consumer {
        validate_push_name(name)?;
        validate_secret_name(&config.tool_secret_binary)?;
        validate_secret_name(&config.tool_secret_binary_sha256)?;
        let entry = validate_consumer(consumer)?;
        // The dependency's own canonical repository is the trigger source:
        // bake it so dep events carry repository+branch+sha provenance, not a
        // bare package name.
        let trigger_repo =
            repository.ok_or_else(|| failure("Push adapters require a manifest repository URL"))?;
        let filename = format!(".crow/push-consumer-{name}.yaml");
        if outputs.contains_key(&PathBuf::from(&filename)) {
            return Err(failure(format!("Duplicate push adapter: {filename}")));
        }
        outputs.insert(
            PathBuf::from(filename),
            substitute(
                include_str!("render/consumer.yaml"),
                config,
                &[
                    ("CCID_DEP_BRANCH", entry.branch.as_str()),
                    ("CCID_CONSUMER_URL", entry.consumer.as_str()),
                    ("CCID_CONSUMER_BRANCH", entry.consumer_branch.as_str()),
                    ("CCID_CONSUMER_JOB", entry.job.as_str()),
                    ("CCID_DEP_NAME", entry.self_name.as_str()),
                    ("CCID_DEP_REPO", trigger_repo),
                ],
            ),
        );
        inventory.push_consumers.insert(
            name.clone(),
            ConsumerPlan {
                consumer: entry.consumer.clone(),
                branch: entry.branch.clone(),
                consumer_branch: entry.consumer_branch.clone(),
                job: entry.job.clone(),
                self_name: entry.self_name.clone(),
            },
        );
    }
    outputs.insert(
        PathBuf::from(INVENTORY),
        serde_json::to_string_pretty(&inventory)? + "\n",
    );

    // Validate the whole destination set before any writes or directory creation.
    for directory in [".ci", ".crow"] {
        if let Some(metadata) = metadata(&repo.join(directory))? {
            if !metadata.is_dir() || metadata.file_type().is_symlink() {
                return Err(failure(format!("Unsafe adapter directory: {directory}")));
            }
        }
    }
    let mut drift = Vec::new();
    for (relative, expected) in &outputs {
        let path = repo.join(relative);
        if let Some(metadata) = metadata(&path)? {
            if !metadata.is_file() || metadata.file_type().is_symlink() {
                return Err(failure(format!(
                    "Unsafe adapter file: {}",
                    relative.display()
                )));
            }
            let actual = fs::read_to_string(path)?;
            if !owned(relative, &actual) {
                return Err(failure(format!(
                    "Refusing to overwrite foreign adapter: {}",
                    relative.display()
                )));
            }
            if actual != *expected {
                drift.push(relative.clone());
            }
        } else {
            drift.push(relative.clone());
        }
    }
    let obsolete = obsolete(repo, &outputs)?;
    if fs::read(repo.join(manifest))? != bytes {
        return Err(failure("Manifest changed during job rendering"));
    }
    if check && (!drift.is_empty() || !obsolete.is_empty()) {
        let paths = drift
            .iter()
            .chain(&obsolete)
            .map(|path| path.display().to_string())
            .collect::<Vec<_>>()
            .join(", ");
        return Err(failure(format!(
            "Generated job adapters have drifted: {paths}"
        )));
    }
    if !check {
        for relative in &drift {
            let path = repo.join(relative);
            let parent = path
                .parent()
                .expect("Generated paths have parent directories");
            fs::create_dir_all(parent)?;
            let mut temporary = tempfile::NamedTempFile::new_in(parent)?;
            temporary.write_all(outputs[relative].as_bytes())?;
            temporary.persist(path)?;
        }
        for relative in &obsolete {
            fs::remove_file(repo.join(relative))?;
        }
    }
    Ok(Report {
        checked: check,
        files: outputs.into_keys().collect(),
        removed: obsolete,
    })
}

/// Single-pass template substitution: tool revision, secret names, then
/// caller pairs. Values are pre-validated (no CCID_, no shell metachars),
/// so substituted text can never reintroduce a placeholder.
fn substitute(template: &str, config: &Config, pairs: &[(&str, &str)]) -> String {
    let mut rendered = template
        .replace("CCID_TOOL_REVISION", &config.tool_revision)
        .replace("CCID_SECRET_BINARY", &config.tool_secret_binary)
        .replace("CCID_SECRET_SHA", &config.tool_secret_binary_sha256);
    for (key, value) in pairs {
        rendered = rendered.replace(key, value);
    }
    rendered
}

fn validate_push_name(name: &str) -> Result<()> {
    if name.is_empty()
        || name.contains("CCID")
        || !name
            .bytes()
            .all(|c| c.is_ascii_alphanumeric() || b"_-".contains(&c))
    {
        return Err(failure(
            "Push adapter names must be plain and avoid the CCID_ prefix",
        ));
    }
    Ok(())
}

fn validate_resolver_token_secret(name: &str) -> Result<()> {
    let bytes = name.as_bytes();
    if bytes.is_empty() || bytes.len() > 64 {
        return Err(failure(
            "Invalid [render].resolver_token_secret: must be 1-64 characters",
        ));
    }
    let first_ok = bytes[0].is_ascii_alphanumeric() || bytes[0] == b'_';
    let rest_ok = bytes[1..]
        .iter()
        .all(|b| b.is_ascii_alphanumeric() || *b == b'_' || *b == b'-' || *b == b'.');
    if !first_ok || !rest_ok {
        return Err(failure(
            "Invalid [render].resolver_token_secret: use [A-Za-z0-9_.-], leading [A-Za-z0-9_]",
        ));
    }
    Ok(())
}

/// Userinfo (and therefore passwords) only exists in scheme URLs; scp-like
/// `user@host:path` carries a login name but never a password.
fn authority_has_userinfo(url: &str) -> bool {
    let rest = url
        .strip_prefix("https://")
        .or_else(|| url.strip_prefix("ssh://"));
    match rest {
        Some(rest) => rest
            .split('/')
            .next()
            .is_some_and(|authority| authority.contains('@')),
        None => false,
    }
}
/// Shell-safe consumer values: they render inside double-quoted adapter
/// strings, so anything beyond plain names and forge URL punctuation fails.
fn validate_consumer(entry: &PushConsumer) -> Result<PushConsumer> {
    for value in [
        &entry.branch,
        &entry.consumer_branch,
        &entry.job,
        &entry.self_name,
    ] {
        if value.is_empty()
            || value.contains("CCID")
            || !value
                .bytes()
                .all(|c| c.is_ascii_alphanumeric() || b"_-".contains(&c))
        {
            return Err(failure(
                "Push consumer branches, jobs and names must be plain",
            ));
        }
    }
    if entry.consumer.is_empty()
        || entry.consumer.contains("CCID")
        || !entry
            .consumer
            .bytes()
            .all(|c| c.is_ascii_alphanumeric() || b"._-:/@".contains(&c))
        || !(entry.consumer.starts_with("https://")
            || entry.consumer.starts_with("ssh://")
            || entry.consumer.starts_with("git@"))
        || authority_has_userinfo(&entry.consumer)
    {
        return Err(failure(
            "Push consumer URL must be a plain forge URL without credentials",
        ));
    }
    Ok(entry.clone())
}
/// Inject the optional resolver token into an already-built Crow adapter.
/// Absent secret returns the input byte-identical (preserving auxiliary
/// source variables). Present secret appends exactly one
/// `CFRG_RESOLVER_FORGEJO_TOKEN: { from_secret: <quoted> }` entry to the
/// repository-job environment; native-status steps are untouched. The secret
/// name is quoted with `serde_json` (valid YAML), never interpreted raw.
/// The jobs that gate landing: the manifest's `[verdict] jobs`, else `verify`
/// when the repository declares such a job, else none (no verdict is posted).
fn gating_jobs(parsed: &crate::Manifest) -> Result<Vec<String>> {
    let jobs: Vec<String> = match &parsed.verdict {
        Some(verdict) => verdict.jobs.clone(),
        None if parsed.jobs.contains_key("verify") => vec!["verify".to_owned()],
        None => vec![],
    };
    for job in &jobs {
        if !parsed.jobs.contains_key(job) {
            return Err(failure(format!("[verdict] names undeclared job: {job}")));
        }
        if !job
            .bytes()
            .all(|b| b.is_ascii_alphanumeric() || b"_.-".contains(&b))
        {
            return Err(failure("[verdict] jobs must be plain job names"));
        }
    }
    let mut unique = jobs.clone();
    unique.sort();
    unique.dedup();
    if unique.len() != jobs.len() {
        return Err(failure("[verdict] jobs must be unique"));
    }
    Ok(jobs)
}

/// Bake the gating jobs into the status steps of a rendered adapter.
fn inject_gating(base: String, gating: &[String]) -> Result<String> {
    if base.matches(GATING_PLACEHOLDER).count() != 2 {
        return Err(failure("Render template lost its verdict placeholders"));
    }
    Ok(base.replace(GATING_PLACEHOLDER, &gating.join(",")))
}

fn inject_resolver_token(
    base: String,
    tool_revision: &str,
    secret: Option<&str>,
) -> Result<String> {
    let Some(secret) = secret else {
        return Ok(base);
    };
    validate_resolver_token_secret(secret)?;
    // serde_json string quoting is valid YAML and escapes control chars.
    let quoted = serde_json::to_string(secret)?;
    let pin_line = format!("      CCID_REVISION: '{tool_revision}'\n");
    if base.matches(&pin_line).count() != 1 {
        return Err(failure("Render template lost its CCID_REVISION pin"));
    }
    let insertion =
        format!("{pin_line}      {RESOLVER_TOKEN_ENV}:\n        from_secret: {quoted}\n");
    Ok(base.replacen(&pin_line, &insertion, 1))
}

fn metadata(path: &Path) -> Result<Option<fs::Metadata>> {
    match fs::symlink_metadata(path) {
        Ok(value) => Ok(Some(value)),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(None),
        Err(error) => Err(error.into()),
    }
}

fn owned(path: &Path, content: &str) -> bool {
    if path == Path::new(INVENTORY) {
        serde_json::from_str::<serde_json::Value>(content)
            .ok()
            .and_then(|value| value.get("generator").cloned())
            .is_some_and(|value| value.as_str() == Some(GENERATOR))
    } else {
        content.starts_with(CROW_MARKER)
    }
}

fn obsolete(repo: &Path, outputs: &BTreeMap<PathBuf, String>) -> Result<Vec<PathBuf>> {
    let directory = repo.join(".crow");
    if !directory.exists() {
        return Ok(Vec::new());
    }
    let mut obsolete = Vec::new();
    for entry in fs::read_dir(directory)? {
        let entry = entry?;
        let relative = Path::new(".crow").join(entry.file_name());
        if outputs.contains_key(&relative)
            || !matches!(
                relative.extension().and_then(|v| v.to_str()),
                Some("yaml" | "yml")
            )
        {
            continue;
        }
        // Never follow or delete an unrelated symlink or directory.
        if entry.file_type()?.is_file() {
            let bytes = fs::read(entry.path())?;
            if bytes.starts_with(CROW_MARKER.as_bytes()) {
                obsolete.push(relative);
            }
        }
    }
    obsolete.sort();
    Ok(obsolete)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sources(text: &str) -> Result<BTreeMap<String, PinnedSource>> {
        let root = tempfile::tempdir().unwrap();
        fs::create_dir_all(root.path().join(".ci")).unwrap();
        fs::write(root.path().join(".ci/archives.toml"), text).unwrap();
        pinned_sources(root.path())
    }

    const FIXTURE: &str = r#"
schema = 1
[archives.stopgap-product]
revision = "5e31e9d852b166e7d3d1d197b269fba675f3680d"
archive_variable = "STOPGAP_PRODUCT_SOURCE_ARCHIVE"
digest_variable = "STOPGAP_PRODUCT_SOURCE_SHA256"
workflows = ["tor-snowflake"]
[archives.cfry]
kind = "git-bundle"
revision = "219611e3dd0c50bbc284bff79f95651453524564"
archive_variable = "CFRY_SOURCE_BUNDLE"
digest_variable = "CFRY_SOURCE_SHA256"
workflows = ["tor-snowflake"]
[archives.shared]
revision = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
archive_variable = "SHARED_SOURCE_ARCHIVE"
digest_variable = "SHARED_SOURCE_SHA256"
"#;

    #[test]
    fn auxiliary_variables_scope_to_declared_workflows() {
        let parsed = sources(FIXTURE).unwrap();
        assert_eq!(parsed.len(), 3);
        let snowflake = workflow_adapter("abc", "tor-snowflake", &parsed).unwrap();
        assert!(snowflake.contains("STOPGAP_PRODUCT_SOURCE_ARCHIVE: {default: \"\"}"));
        assert!(snowflake.contains("STOPGAP_PRODUCT_SOURCE_SHA256: {default: \"\"}"));
        assert!(snowflake.contains("CFRY_SOURCE_BUNDLE: {default: \"\"}"));
        assert!(snowflake.contains("CFRY_SOURCE_SHA256: {default: \"\"}"));
        assert!(snowflake.contains("SHARED_SOURCE_ARCHIVE: {default: \"\"}"));
        let other = workflow_adapter("abc", "tor-private", &parsed).unwrap();
        assert!(!other.contains("STOPGAP_PRODUCT_SOURCE_ARCHIVE"));
        assert!(!other.contains("CFRY_SOURCE_BUNDLE"));
        assert!(other.contains("SHARED_SOURCE_ARCHIVE: {default: \"\"}"));
        let verify = workflow_adapter("abc", "repository-jobs", &parsed).unwrap();
        assert!(!verify.contains("STOPGAP_PRODUCT_SOURCE_ARCHIVE"));
        assert!(verify.contains("SHARED_SOURCE_ARCHIVE: {default: \"\"}"));
    }

    #[test]
    fn empty_selection_keeps_template_byte_identical() {
        // Only a workflow-scoped entry here, so an unrelated workflow selects
        // nothing; the shared (unscoped) entry is covered by the scoping test.
        let text = r#"
schema = 1
[archives.stopgap-product]
revision = "5e31e9d852b166e7d3d1d197b269fba675f3680d"
archive_variable = "STOPGAP_PRODUCT_SOURCE_ARCHIVE"
digest_variable = "STOPGAP_PRODUCT_SOURCE_SHA256"
workflows = ["tor-snowflake"]
"#;
        let parsed = sources(text).unwrap();
        let expected = include_str!("render/crow.yaml").replace("CCID_TOOL_REVISION", "abc");
        assert_eq!(
            workflow_adapter("abc", "unrelated-workflow", &parsed).unwrap(),
            expected
        );
        let root = tempfile::tempdir().unwrap();
        let empty = pinned_sources(root.path()).unwrap();
        assert!(empty.is_empty());
        assert_eq!(
            workflow_adapter("abc", "tor-snowflake", &empty).unwrap(),
            expected
        );
    }

    fn live_manifest(text: &str) -> tempfile::TempDir {
        let root = tempfile::tempdir().unwrap();
        fs::create_dir_all(root.path().join(".ci")).unwrap();
        fs::write(root.path().join(".ci/live-inputs.toml"), text).unwrap();
        root
    }

    const LIVE_FIXTURE: &str = r#"
schema = 1
[live-inputs.v01-source-bundle]
archive_variable = "V01_SOURCE_BUNDLE"
digest_variable = "V01_SOURCE_BUNDLE_SHA256"
sha256 = "a89129a0f4e827c807f1453ef40c5968d1a063267d4be8741783abdaa31e82b6"
default_path = "/workspaces/ci-sources/v01-tor-records/a89129a0f4e827c807f1453ef40c5968d1a063267d4be8741783abdaa31e82b6.tar"
workflows = ["v01-tor-live"]
[live-inputs.v01-root-source]
archive_variable = "V01_ROOT_SOURCE_ARCHIVE"
digest_variable = "V01_ROOT_SOURCE_SHA256"
sha256 = "a84b41fcf68d71507db9e46072c3c329ec1b2667114c38fe3ff275bd7ab6cb1d"
default_path = "/workspaces/ci-sources/146/a84b41fcf68d71507db9e46072c3c329ec1b2667114c38fe3ff275bd7ab6cb1d.tar"
commit = "bb0f72d89dbfc5323580205740139fc84cc7a284"
workflows = ["v01-tor-live"]
[live-tools.receipt]
path = "/workspaces/component-releases/cmsg/20a55ac8159811bbac7c8370ae7f28fc075f2153/tor-tools/tools.json"
sha256 = "b3a64bbc373b886dc164e859c1d26e7a4055a7d65b8c2556a0bd2cff4ac152e0"
[diag.discovery-lib]
file = "src/tor_discovery.rs"
sha256 = "fc6c8db74254e6246bb6da69228e4afe2c17ff42575133bb3ab1b530d2c30041"
diagnostic_sha256 = "f67ec53ed7f19e9bf7293eca631a24687b14fc2558109269edcbd901fade91d7"
[live-drivers.harness]
file = ".ci/v01-tor-live.py"
sha256 = "20314ee07fc2adaae05c4018268abec49865c2a78e0710519fa55de0b1c5cc5b"
"#;

    #[test]
    fn live_inputs_declare_scoped_workflow_variables() {
        let root = live_manifest(LIVE_FIXTURE);
        let parsed = live_inputs(root.path()).unwrap();
        assert_eq!(parsed.len(), 2);
        let rendered = workflow_adapter("abc", "v01-tor-live", &parsed).unwrap();
        assert!(rendered.contains("V01_SOURCE_BUNDLE: {default: \"\"}"));
        assert!(rendered.contains("V01_SOURCE_BUNDLE_SHA256: {default: \"\"}"));
        assert!(rendered.contains("V01_ROOT_SOURCE_ARCHIVE: {default: \"\"}"));
        assert!(rendered.contains("V01_ROOT_SOURCE_SHA256: {default: \"\"}"));
        let other = workflow_adapter("abc", "tor-records", &parsed).unwrap();
        assert!(!other.contains("V01_SOURCE_BUNDLE"));
        let absent = tempfile::tempdir().unwrap();
        assert!(live_inputs(absent.path()).unwrap().is_empty());
    }

    #[test]
    fn live_inputs_reject_drifted_declarations() {
        // Shape-valid digests parse; tampering is caught at runtime digest
        // verification, not at render.
        let tampered = LIVE_FIXTURE.replace("a89129a0", "b89129a0");
        assert!(live_inputs(live_manifest(&tampered).path()).is_ok());
        let unknown_key = LIVE_FIXTURE.replace("sha256 = ", "digest = ");
        assert!(live_inputs(live_manifest(&unknown_key).path()).is_err());
        let relative = LIVE_FIXTURE.replace("/workspaces/", "workspaces/");
        assert!(live_inputs(live_manifest(&relative).path()).is_err());
        let bad_commit = LIVE_FIXTURE.replace("bb0f72d89dbfc5323580205740139fc84cc7a284", "xyz");
        assert!(live_inputs(live_manifest(&bad_commit).path()).is_err());
        let unscoped = LIVE_FIXTURE.replace("workflows = [\"v01-tor-live\"]", "workflows = []");
        assert!(live_inputs(live_manifest(&unscoped).path()).is_err());
    }

    #[test]
    fn template_variable_set_is_pinned() {
        let template = include_str!("render/crow.yaml");
        let section = template
            .split_once("variables:")
            .expect("template has a variables section");
        let section = section
            .1
            .split_once("steps:")
            .expect("template has steps")
            .0;
        let mut names = Vec::new();
        for line in section.lines() {
            let Some(declaration) = line.strip_prefix("  ") else {
                continue;
            };
            let Some((name, default)) = declaration.split_once(": {default: ") else {
                continue;
            };
            if !name.is_empty()
                && name
                    .bytes()
                    .all(|byte| byte.is_ascii_uppercase() || byte == b'_' || byte.is_ascii_digit())
                && default.starts_with('"')
                && default.ends_with('}')
            {
                names.push(name.to_owned());
            }
        }
        names.sort();
        let mut expected: Vec<String> =
            TEMPLATE_VARIABLES.iter().map(ToString::to_string).collect();
        expected.sort();
        assert_eq!(names, expected);
    }

    #[test]
    fn duplicate_and_reserved_variables_fail() {
        let duplicate = FIXTURE.to_owned()
            + "\n[archives.second]\nrevision = \"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\"\narchive_variable = \"CFRY_SOURCE_BUNDLE\"\ndigest_variable = \"SECOND_SOURCE_SHA256\"\n";
        assert!(sources(&duplicate).is_err());
        let reserved = FIXTURE.replace("CFRY_SOURCE_BUNDLE", "CI_TOOL_BINARY");
        assert!(sources(&reserved).is_err());
        let reserved_digest = FIXTURE.replace("CFRY_SOURCE_SHA256", "CROW_CACHE");
        assert!(sources(&reserved_digest).is_err());
        let collide_template = FIXTURE.replace("CFRY_SOURCE_BUNDLE", "SOURCE_ARCHIVE");
        assert!(sources(&collide_template).is_err());
    }

    #[test]
    fn malformed_declarations_fail() {
        for (case, text) in [
            ("schema", "schema = 2\n[archives.a]\nrevision = \"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\"\narchive_variable = \"A_SOURCE_ARCHIVE\"\ndigest_variable = \"A_SOURCE_SHA256\"\n"),
            ("revision", "schema = 1\n[archives.a]\nrevision = \"xyz\"\narchive_variable = \"A_SOURCE_ARCHIVE\"\ndigest_variable = \"A_SOURCE_SHA256\"\n"),
            ("kind", "schema = 1\n[archives.a]\nkind = \"tarball\"\nrevision = \"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\"\narchive_variable = \"A_SOURCE_ARCHIVE\"\ndigest_variable = \"A_SOURCE_SHA256\"\n"),
            ("workflows", "schema = 1\n[archives.a]\nrevision = \"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\"\narchive_variable = \"A_SOURCE_ARCHIVE\"\ndigest_variable = \"A_SOURCE_SHA256\"\nworkflows = []\n"),
            ("name", "schema = 1\n[archives.Bad-Name!]\nrevision = \"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\"\narchive_variable = \"A_SOURCE_ARCHIVE\"\ndigest_variable = \"A_SOURCE_SHA256\"\n"),
            ("keys", "schema = 1\n[archives.a]\nrevision = \"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\"\n"),
            ("extra", "schema = 1\n[archives.a]\nrevision = \"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\"\narchive_variable = \"A_SOURCE_ARCHIVE\"\ndigest_variable = \"A_SOURCE_SHA256\"\nowner = \"x\"\n"),
        ] {
            assert!(sources(text).is_err(), "{case}");
        }
    }
}
